# This generates a copy of the ElasticSearch CA certificate in the chart
# namespace.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elastic_cert_arkime }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  namespace: arkime
  annotations:
    # This needs to be in place before the firstrun.yaml Job runs
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  elastic_ca.crt: {{ get (lookup "v1" "Secret" "dataplane-ek" .Values.elastic_cert).data "ca.crt" | default "asdf" }}
