---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: arkime
  name: arkime
  namespace: arkime
spec:
  ports:
  - name: "webgui"
    port: 8443
    targetPort: {{ .Values.listen_port }}
  selector:
    app: arkime-viewer
  type: ClusterIP
