---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: arkime
  name: arkime-viewer
  namespace: arkime
spec:
  ports:
  - name: "http-webgui"
    port: {{ .Values.listen_port }}
    targetPort: {{ .Values.listen_port }}
  selector:
    app: arkime-viewer
  type: ClusterIP
