name: Package Arkime
run-name: ${{github.actor}} is building the Arkime Zarf Package
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-zarf
      - uses: ./.github/actions/registry-login
        with:
          registry_username: ${{secrets.REGISTRY1_USERNAME}}
          registry_password: ${{secrets.REGISTRY1_PASSWORD}}
          registry_url: registry1.dso.mil
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          role-session-name: arkime
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v1
        name: login-ecr
        id: login-ecr
      - uses: ./.github/actions/package-create
      - uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2 # default
          verbose: false # default
          arch: amd64 # allowed values: amd64, arm64
          rootdir: "" # defaults to "PWD"
          workdir: "" # defaults to "PWD/unfor19-awscli"
      - uses: ./.github/actions/s3-publish
        with:
          aws_bucket: ${{secrets.AWS_BUCKET}}
          source: "zarf-package-arkime-amd64.tar.zst"
          destination: "${{github.repository}}/${{ github.head_ref || github.ref_name }}/zarf-package-arkime-amd64.tar.zst"
